export default {
    'Sunny': 'Nhiều nắng',
    'Clear': 'Trời quang',
    'Partly Cloudy': 'Có Mây',
    'Cloudy': 'Nhiều mây',
    'Overcast': 'U ám',
    'Mist': 'Sương mù',
    'Patchy rain nearby': 'Mưa lả tả gần đó',
    'Patchy snow nearby': 'Tuyết rơi lả tả gần đó',
    'Patchy sleet nearby': 'Mưa tuyết lả tả gần đó',
    'Patchy freezing drizzle nearby': 'Mưa phùn băng giá lả tả gần đó',
    'Thundery outbreaks in nearby': 'Các cơn giông tố nổi lên gần đó',
    'Blowing snow': 'Tuyết thổi mạnh',
    'Blizzard': 'Trận bão tuyết',
    'Fog': 'Sương mù',
    'Freezing fog': 'Sương mù băng giá',
    'Patchy light drizzle': 'Mưa phùn nhẹ lả tả',
    'Light drizzle': 'Mưa phùn nhẹ',
    'Freezing drizzle': 'Mưa phùn băng giá',
    'Heavy freezing drizzle': 'Mưa phùn nặng băng giá',
    'Patchy light rain': 'Mưa nhẹ lả tả',
    'Light rain': 'Mưa nhẹ',
    'Moderate rain at times': 'Thỉnh thoảng mưa vừa',
    'Moderate rain': 'Mưa vừa',
    'Heavy rain at times': 'Thỉnh thoảng mưa nặng hạt',
    'Heavy rain': 'Mưa rơi nặng hạt',
    'Light freezing rain': 'Mưa giá rét nhẹ',
    'Moderate or heavy freezing rain': 'Mưa giá rét Vừa hoặc Nặng Hạt',
    'Light sleet': 'Mưa tuyết nhẹ',
    'Moderate or heavy sleet': 'Mưa tuyết vừa hoặc nặng hạt',
    'Patchy light snow': 'Tuyết nhẹ lả tả',
    'Light snow': 'Tuyết nhẹ',
    'Patchy moderate snow': 'Tuyết vừa lả tả',
    'Moderate snow': 'Tuyết vừa',
    'Patchy heavy snow': 'Tuyết rơi nặng hạt lả tả',
    'Heavy snow': 'Tuyết rơi nặng hạt',
    'Ice pellets': 'Mưa đá',
    'Light rain shower': 'Mưa rào nhẹ',
    'Moderate or heavy rain shower': 'Mưa rào vừa hoặc nặng hạt',
    'moderate or heavy rain with thunder': 'Mưa rào vừa hoặc nặng hạt với sấm sét',
    'Torrential rain shower': 'Mưa rào xối xả',
    'Light sleet showers': 'Mưa tuyết rào nhẹ',
    'Moderate or heavy sleet showers': 'Mưa tuyết rào vừa hoặc nặng hạt',
    'Light snow showers': 'Mưa rào lẫn tuyết nhẹ',
    'Moderate or heavy snow showers': 'Mưa rào lẫn tuyết vừa hoặc nặng hạt',
    'Light showers of ice pellets': 'Mưa đá rào nhẹ',
    'Moderate or heavy showers of ice pellets': 'Mưa đá rào vừa hoặc nặng hạt',
    'Patchy light rain in area with thunder': 'Mưa nhẹ lả tả trong khu vực có sấm sét',
    'Moderate or heavy rain in area with thunder': 'Mưa vừa hoặc nặng hạt trong khu vực có sấm sét',
    'Patchy light snow in area with thunder': 'Tuyết nhẹ lả tả trong khu vực có sấm sét',
    'Moderate or heavy snow in area with thunder': 'Tuyết vừa hoặc nặng hạt trong khu vực có sấm sét',
    'sunny': 'Nhiều nắng',
    'clear': 'Trời quang',
    'partly cloudy': 'Có Mây',
    'cloudy': 'Nhiều mây',
    'overcast': 'U ám',
    'mist': 'Sương mù',
    'patchy rain nearby': 'Mưa lả tả gần đó',
    'patchy snow nearby': 'Tuyết rơi lả tả gần đó',
    'patchy sleet nearby': 'Mưa tuyết lả tả gần đó',
    'patchy freezing drizzle nearby': 'Mưa phùn băng giá lả tả gần đó',
    'thundery outbreaks in nearby': 'Các cơn giông tố nổi lên gần đó',
    'blowing snow': 'Tuyết thổi mạnh',
    'blizzard': 'Trận bão tuyết',
    'fog': 'Sương mù',
    'freezing fog': 'Sương mù băng giá',
    'patchy light drizzle': 'Mưa phùn nhẹ lả tả',
    'light drizzle': 'Mưa phùn nhẹ',
    'freezing drizzle': 'Mưa phùn băng giá',
    'heavy freezing drizzle': 'Mưa phùn nặng băng giá',
    'patchy light rain': 'Mưa nhẹ lả tả',
    'light rain': 'Mưa nhẹ',
    'moderate rain at times': 'Thỉnh thoảng mưa vừa',
    'moderate rain': 'Mưa vừa',
    'heavy rain at times': 'Thỉnh thoảng mưa nặng hạt',
    'heavy rain': 'Mưa rơi nặng hạt',
    'light freezing rain': 'Mưa giá rét nhẹ',
    'moderate or heavy freezing rain': 'Mưa giá rét Vừa hoặc Nặng Hạt',
    'light sleet': 'Mưa tuyết nhẹ',
    'moderate or heavy sleet': 'Mưa tuyết vừa hoặc nặng hạt',
    'patchy light snow': 'Tuyết nhẹ lả tả',
    'light snow': 'Tuyết nhẹ',
    'patchy moderate snow': 'Tuyết vừa lả tả',
    'moderate snow': 'Tuyết vừa',
    'patchy heavy snow': 'Tuyết rơi nặng hạt lả tả',
    'heavy snow': 'Tuyết rơi nặng hạt',
    'ice pellets': 'Mưa đá',
    'light rain shower': 'Mưa rào nhẹ',
    'moderate or heavy rain shower': 'Mưa rào vừa hoặc nặng hạt',
    'torrential rain shower': 'Mưa rào xối xả',
    'light sleet showers': 'Mưa tuyết rào nhẹ',
    'moderate or heavy sleet showers': 'Mưa tuyết rào vừa hoặc nặng hạt',
    'light snow showers': 'Mưa rào lẫn tuyết nhẹ',
    'moderate or heavy snow showers': 'Mưa rào lẫn tuyết vừa hoặc nặng hạt',
    'light showers of ice pellets': 'Mưa đá rào nhẹ',
    'moderate or heavy showers of ice pellets': 'Mưa đá rào vừa hoặc nặng hạt',
    'patchy light rain in area with thunder': 'Mưa nhẹ lả tả trong khu vực có sấm sét',
    'moderate or heavy rain in area with thunder': 'Mưa vừa hoặc nặng hạt trong khu vực có sấm sét',
    'patchy light snow in area with thunder': 'Tuyết nhẹ lả tả trong khu vực có sấm sét',
    'moderate or heavy snow in area with thunder': 'Tuyết vừa hoặc nặng hạt trong khu vực có sấm sét',
}